### ISSUE TITLE
docker-compose.yml empty

### ISSUE THREAD

**Issue by xinmans** [easychen/CookieCloud#13]
pls check

**Comment by sparanoid** [comment]
docker-compose version can be as simple as:

```yml
  cookiecloud:
    image: easychen/cookiecloud:latest
    ports:
      - 8088:8088
```
