### ISSUE TITLE
建议加上docker-compose部署yml

### ISSUE THREAD

**Issue by aitixiong** [easychen/CookieCloud#42]
测试好的yml文件

```yml
version: '2'
services:
  cookiecloud:
    image: easychen/cookiecloud:latest
    container_name: cookiecloud-app
    restart: always
    volumes:
      - ./data:/data/api/data
    ports:
      - 8088:8088
```
